### PR TITLE
Version 0.6.7

### PR DESCRIPTION
**Pull request by xazms**
Summary of Changes
This update introduces enhanced error handling across several classes, ensuring more reliable detection of issues during execution. The primary improvements and new functionalities include:

1. Improved Error Handling:

   - Introduced RuntimeError raising in key methods across DataFrameTransformer, DataQualityManager, and DataStorageManager to ensure any errors are propagated, which allows for better handling by orchestrating systems (e.g., ADF).
   - Enhanced logging within each class for better traceability, including detailed error logs and additional context where exceptions are raised.

2. XLSX File Processing:

   - Added support for reading and processing XLSX files within DataFrameTransformer, expanding the range of supported file formats.
   - Implemented methods to handle binary XLSX files, convert them to DataFrames, and seamlessly integrate them into existing processing pipelines.
   - Improved logging to include information on the specific XLSX sheets and columns processed for better traceability.

3. SQL Query Execution Enhancements:

   - Additional validation steps were added to SQL-related methods, including generate_merge_sql, generate_feedback_timestamps, and execute_feedback_sql, ensuring more reliable query execution and feedback handling.
   - Expanded error logging in SQL execution functions to capture detailed error information, making debugging easier.

4. Documentation and Logging Improvements:

   - Improved in-method documentation to clarify method purposes and workflows.
   - Enhanced logging of major steps within key processes, including start/end of operations, to make debugging and traceability easier.

These changes significantly enhance the robustness of the data processing and quality-checking workflows and provide support for XLSX files, allowing for more versatile data handling capabilities.

### CODE REVIEW

**Review by xazms — COMMENTED** [review]
Reviewed

**Review by xazms — COMMENTED** [review]
Reviued once again

**Comment by xazms** [comment]
PR is ready for approval

**Review by BDJensen — APPROVED** [review]
looks good

**Pull request merged**
